export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES'
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS'
export const FETCH_REPOSITORIES_FAIL = 'FETCH_REPOSITORIES_FAIL'

export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE'

export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS'
